<?php
require_once 'includes/header.php';

$userId = getUserId();
$message = '';
$error = '';

$config = include __DIR__ . '/config/mail.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['save_email_settings'])) {
        $smtpHost = trim($_POST['smtp_host'] ?? 'smtp.gmail.com');
        $smtpPort = (int)($_POST['smtp_port'] ?? 587);
        $smtpUsername = trim($_POST['smtp_username'] ?? '');
        $smtpPassword = trim($_POST['smtp_password'] ?? '');
        $fromName = trim($_POST['from_name'] ?? 'Moonday Task Manager');
        $fromEmail = trim($_POST['from_email'] ?? $smtpUsername);
        $enabled = isset($_POST['enabled']) ? 'true' : 'false';
        $notifyAll = isset($_POST['notify_all']) ? 'true' : 'false';
        $notifyOwner = isset($_POST['notify_owner']) ? 'true' : 'false';

        $smtpSecure = $smtpPort == 465 ? 'ssl' : 'tls';
    $content = <<<PHP
<?php
/**
 * Mail Configuration - Auto-generated by Email Settings
 * DO NOT edit manually unless you know what you're doing
 */
return [
    'smtp_host'     => '{$smtpHost}',
    'smtp_port'     => {$smtpPort},
    'smtp_secure'   => '{$smtpSecure}',
    'smtp_username' => '{$smtpUsername}',
    'smtp_password' => '{$smtpPassword}',
    'from_name'     => '{$fromName}',
    'from_email'    => '{$fromEmail}',
    'enabled'       => {$enabled},
    'notify_all'    => {$notifyAll},
    'notify_owner'  => {$notifyOwner},
];
PHP;

        if (file_put_contents(__DIR__ . '/config/mail.php', $content)) {
            $message = 'Pengaturan email berhasil disimpan!';
            $config = include __DIR__ . '/config/mail.php';
        } else {
            $error = 'Gagal menyimpan pengaturan. Pastikan file config/mail.php writable.';
        }
    }

    if (isset($_POST['test_email'])) {
        require_once 'includes/mail_helper.php';
        $email = $_SESSION['email'] ?? '';
        if ($email) {
            $config = include __DIR__ . '/config/mail.php';
            if (!$config['enabled'] || empty($config['smtp_username'])) {
                $error = 'Aktifkan email notification dan isi SMTP settings terlebih dahulu.';
            } else {
                $html = getEmailTemplate('Test Email', 'Ini adalah email test dari Moonday.', 'Medium', 'To Do', 'Test', '-', 'System', getSiteUrl());
                $text = "Ini adalah email test dari Moonday Task Manager.";
                simpleMail($config, $email, $_SESSION['full_name'] ?? 'User', '[Moonday] Test Email', $html, $text);
                $message = 'Email test dikirim ke ' . $email . '. Cek inbox/spam kamu.';
            }
        } else {
            $error = 'Email belum diatur di profil.';
        }
    }
}
?>

<div class="page-header">
    <div>
        <h1 class="page-title">📧 Pengaturan Email</h1>
        <p class="page-subtitle">Konfigurasi notifikasi email saat tugas baru dibuat</p>
    </div>
    <a href="profile.php" class="btn btn-outline">← Kembali</a>
</div>

<?php if ($message): ?>
    <div class="alert alert-success">✅ <?= htmlspecialchars($message) ?></div>
<?php endif; ?>
<?php if ($error): ?>
    <div class="alert alert-danger">⚠️ <?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<div class="grid-2">
    <div>
        <div class="card" style="margin-bottom: 24px;">
            <div class="card-header">
                <h2 class="card-title">⚙️ SMTP Server</h2>
            </div>
            <div class="card-body">
                <form method="POST">
                    <div class="form-group">
                        <label>SMTP Host</label>
                        <input type="text" name="smtp_host" class="form-control" value="<?= htmlspecialchars($config['smtp_host'] ?? 'smtp.gmail.com') ?>" placeholder="smtp.gmail.com">
                        <small style="color:var(--gray-500);font-size:12px;">Gmail: smtp.gmail.com, Outlook: smtp-mail.outlook.com</small>
                    </div>

                    <div class="grid-2">
                        <div class="form-group">
                            <label>SMTP Port</label>
                            <select name="smtp_port" class="form-control">
                                <option value="587" <?= ($config['smtp_port'] ?? 587) == 587 ? 'selected' : '' ?>>587 (TLS)</option>
                                <option value="465" <?= ($config['smtp_port'] ?? 587) == 465 ? 'selected' : '' ?>>465 (SSL)</option>
                                <option value="25" <?= ($config['smtp_port'] ?? 587) == 25 ? 'selected' : '' ?>>25</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>From Name</label>
                            <input type="text" name="from_name" class="form-control" value="<?= htmlspecialchars($config['from_name'] ?? 'Moonday Task Manager') ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label>SMTP Username (Email)</label>
                        <input type="email" name="smtp_username" class="form-control" value="<?= htmlspecialchars($config['smtp_username'] ?? '') ?>" placeholder="your@email.com">
                    </div>

                    <div class="form-group">
                        <label>SMTP Password</label>
                        <input type="password" name="smtp_password" class="form-control" value="<?= htmlspecialchars($config['smtp_password'] ?? '') ?>" placeholder="App password / password email">
                        <small style="color:var(--gray-500);font-size:12px;">Untuk Gmail: gunakan App Password, bukan password akun</small>
                    </div>

                    <div class="form-group">
                        <label>From Email (opsional, default = SMTP Username)</label>
                        <input type="email" name="from_email" class="form-control" value="<?= htmlspecialchars($config['from_email'] ?? '') ?>" placeholder="Sama dengan username">
                    </div>

                    <div style="display:flex;gap:24px;margin-top:16px;">
                        <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:14px;">
                            <input type="checkbox" name="enabled" <?= $config['enabled'] ? 'checked' : '' ?> style="width:auto;margin:0;">
                            Aktifkan notifikasi email
                        </label>
                    </div>

                    <div style="display:flex;gap:24px;margin-top:12px;">
                        <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:14px;">
                            <input type="checkbox" name="notify_all" <?= !empty($config['notify_all']) ? 'checked' : '' ?> style="width:auto;margin:0;">
                            Kirim ke semua user
                        </label>
                        <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:14px;">
                            <input type="checkbox" name="notify_owner" <?= !empty($config['notify_owner']) ? 'checked' : '' ?> style="width:auto;margin:0;">
                            Kirim juga ke pembuat tugas
                        </label>
                    </div>

                    <div style="display:flex;gap:12px;margin-top:24px;">
                        <button type="submit" name="save_email_settings" class="btn btn-primary">💾 Simpan Pengaturan</button>
                        <button type="submit" name="test_email" class="btn btn-outline">📤 Kirim Test Email</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div>
        <div class="card" style="margin-bottom: 24px;">
            <div class="card-header">
                <h2 class="card-title">📖 Panduan Setup</h2>
            </div>
            <div class="card-body" style="font-size:14px;color:var(--gray-700);">
                <h4 style="margin:0 0 8px;color:var(--gray-900);">Gmail:</h4>
                <ol style="margin:0 0 16px;padding-left:20px;">
                    <li>Buka <a href="https://myaccount.google.com/apppasswords" target="_blank">Google App Passwords</a></li>
                    <li>Buat app password baru (pilih "Other")</li>
                    <li>Copy 16 karakter password yang muncul</li>
                    <li>Paste di field SMTP Password</li>
                </ol>

                <h4 style="margin:16px 0 8px;color:var(--gray-900);">cPanel Email:</h4>
                <ol style="margin:0;padding-left:20px;">
                    <li>Buat email account di cPanel</li>
                    <li>SMTP Host: <code>mail.domainkamu.com</code></li>
                    <li>SMTP Port: 465 (SSL)</li>
                    <li>Username & Password: sesuai email yang dibuat</li>
                </ol>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h2 class="card-title">ℹ️ Info</h2>
            </div>
            <div class="card-body" style="font-size:14px;color:var(--gray-600);">
                <p>Email notifikasi akan dikirim saat:</p>
                <ul style="margin:8px 0;padding-left:20px;">
                    <li>Tugas baru dibuat via <strong>add_task.php</strong></li>
                    <li>Tugas baru dibuat via AI Chat</li>
                </ul>
                <p>Email yang menerima notifikasi:</p>
                <ul style="margin:8px 0;padding-left:20px;">
                    <li>Semua user (jika "Kirim ke semua user" aktif)</li>
                    <li>Atau hanya pembuat tugas</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php require_once 'includes/footer.php'; ?>
