<?php
/**
 * Mail Configuration - Auto-generated by Email Settings
 * DO NOT edit manually unless you know what you're doing
 */
return [
    'smtp_host'     => 'smtp.gmail.com',
    'smtp_port'     => 465,
    'smtp_secure'   => 'ssl',
    'smtp_username' => 'moontzyn@gmail.com',
    'smtp_password' => 'vsze jmib hubn lvly',
    'from_name'     => 'Moonday Task Manager',
    'from_email'    => '',
    'enabled'       => true,
    'notify_all'    => true,
    'notify_owner'  => true,
];